# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcec44bfd7bf5c6c90667389c29ed4e86114613741dc27e413326ff15ea85906295b4084cf85225a30caee86513e80604ec9bcf6e73869e5f90b63f4affc378d

test:
  secret_key_base: d49e3d9f29346035710b86f88aa8436e6ed912ff4884d59b8c8832d9421c91d706acf794118c6b78da5018b8c2911d14010b80428db3a2740ffba85fa6ff614c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
